index:
    path: /
    controller: App\Controller\DefaultController::index

book_detail: 
    path: /books/{bookid}.html
    controller: App\Controller\BookController::detail
    requirements: 
        bookid: '\d{5}'
